name: Build Website

on:
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print info
      run: echo $PWD


    - name: Clone branch gh-pages
      uses: actions/checkout@v2
      with:
        path: 'gh-pages'
        ref: gh-pages

    - name: Print info
      run: echo $PWD && ls
